import type { Metadata } from 'next';
import { inter } from './fonts';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head>
				<script src="https://unpkg.com/react-scan/dist/auto.global.js" async />
			</head>
			<body
				className={cn(
					'min-h-screen bg-base-100 font-sans antialiased bg-cell',
					inter.className,
				)}
			>
				<ThemeProvider
					attribute="data-theme"
					disableTransitionOnChange
					defaultTheme="system"
					enableSystem
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
