import type { Metadata } from 'next';
import { inter } from './fonts';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { cn } from '@/lib/utils';
import { DialogProvider } from '@/components/Dialog/provider';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={cn(
				'bg-base-200 font-sans text-base antialiased',
				inter.className,
			)}
			suppressHydrationWarning
		>
			<head>
				{/* <script src="https://unpkg.com/react-scan/dist/auto.global.js" async /> */}
			</head>
			<body>
				<ThemeProvider
					attribute="data-theme"
					disableTransitionOnChange
					defaultTheme="system"
					enableSystem
				>
					<DialogProvider>{children}</DialogProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
