// Generated by dayjs-nuxt-module
import dayjs from 'dayjs'
import relativeTime from 'dayjs/plugin/relativeTime.js'
import updateLocale from 'dayjs/plugin/updateLocale.js'
import utc from 'dayjs/plugin/utc.js'

dayjs.extend(updateLocale)
dayjs.extend(relativeTime)
dayjs.extend(utc)

export function useDayjs() {
  return dayjs
}
